lock-version = "1.0"
created-by = "pip"

[[packages]]
name = "build"
version = "1.4.0"

[[packages.wheels]]
name = "build-1.4.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/c5/0d/84a4380f930db0010168e0aa7b7a8fed9ba1835a8fbb1472bc6d0201d529/build-1.4.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "6a07c1b8eb6f2b311b96fcbdbce5dab5fe637ffda0fd83c9cac622e927501596"

[[packages]]
name = "colorama"
version = "0.4.6"

[[packages.wheels]]
name = "colorama-0.4.6-py2.py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/d1/d6/3965ed04c63042e047cb6a3e6ed1a63a35087b6a609aa3a15ed8ac56c221/colorama-0.4.6-py2.py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "4f1d9991f5acc0ca119f9d443620b77f9d6b33703e51011c16baf57afb285fc6"

[[packages]]
name = "packaging"
version = "26.0rc2"

[[packages.wheels]]
name = "packaging-26.0rc2-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/60/eb/1f8f5e3b10748612b075b2b991d6c4342d993008d2aa05f5c872a4e7bfa5/packaging-26.0rc2-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "885e01b9dbe4913e5080fa516b8550d43ef38549088c63e6e8bb51cd25adea4a"

[[packages]]
name = "pyproject-hooks"
version = "1.2.0"

[[packages.wheels]]
name = "pyproject_hooks-1.2.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/bd/24/12818598c362d7f300f18e74db45963dbcb85150324092410c8b49405e42/pyproject_hooks-1.2.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "9e5c6bfa8dcc30091c74b0cf803c81fdd29d94f01992a7707bc97babb1141913"

[[packages]]
name = "setuptools"
version = "80.9.0"

[[packages.wheels]]
name = "setuptools-80.9.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/a3/dc/17031897dae0efacfea57dfd3a82fdd2a2aeb58e0ff71b77b87e44edc772/setuptools-80.9.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "062d34222ad13e0cc312a4c02d73f059e86a4acbfbdea8f8f76b28c99f306922"

[[packages]]
name = "sqlite-bro"
version = "0.13.1"

[[packages.wheels]]
name = "sqlite_bro-0.13.1-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/2a/b3/81b91f5b26fff329c59dbf826a87637bd51d1903120427912322f86e7d33/sqlite_bro-0.13.1-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "c26033b0af133049ca578b5fd30b2372f002e7ff934b39774aa4d2da7638c23d"

[[packages]]
name = "sv-ttk"
version = "2.6.0"

[[packages.wheels]]
name = "sv_ttk-2.6.0-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/0f/3d/be0abc3202e90f282ad465f4e7c6e41bc8dce810ce5d1611566a1e7dfba8/sv_ttk-2.6.0-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "4319c52edf2e14732fe84bdc9788e26f9e9a1ad79451ec0f89f0120ffc8105d9"

[[packages]]
name = "wheel"
version = "0.45.1"

[[packages.wheels]]
name = "wheel-0.45.1-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/0b/2c/87f3254fd8ffd29e4c02732eee68a83a1d3c346ae39bc6822dcbcb697f2b/wheel-0.45.1-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "708e7481cc80179af0e556bbf0cc00b8444c7321e2700b8d8580231d13017248"

[[packages]]
name = "wppm"
version = "17.2.20250823"

[[packages.wheels]]
name = "wppm-17.2.20250823-py3-none-any.whl"
url = "https://files.pythonhosted.org/packages/ae/a9/2581cc7f91354eada41367bf68b91b1b7fba6cb6fb469f500dbaf6191539/wppm-17.2.20250823-py3-none-any.whl"

[packages.wheels.hashes]
sha256 = "0945411b12eaf6da134a9d8662a4afb2b25e129dd34fc2f6ef76ee62d61411c3"
